export enum BattlePosition {
  Attack = "ATTACK_POSITION",
  Defence = "DEFENCE_POSITION",
}

export enum Orientation {
  FaceDown = "FACE_DOWN",
  FaceUp = "FACE_UP",
}

export enum RowKey {
  Hand = "hand",
  SpellTrap = "spellTrapZones",
  Monster = "monsterZones",
}

export enum DuellistKey {
  Player = "p1",
  Opponent = "p2",
}

export enum Field {
  Arena = "Arena",
  Yami = "Yami",
  Wasteland = "Wasteland",
  Mountain = "Mountain",
  Sogen = "Sogen",
  Umi = "Umi",
  Forest = "Forest",
}

export enum Monster {
  BlueEyesWhiteDragon = "Blue-Eyes White Dragon",
  MysticalElf = "Mystical Elf",
  HitotsuMeGiant = "Hitotsu-Me Giant",
  BabyDragon = "Baby Dragon",
  RyuKishin = "Ryu-Kishin",
  FeralImp = "Feral Imp",
  WingedDragonGuardianOfTheFortress1 = "Winged Dragon, Guardian of the Fortress #1",
  MushroomMan = "Mushroom Man",
  ShadowSpecter = "Shadow Specter",
  BlacklandFireDragon = "Blackland Fire Dragon",
  SwordArmOfDragon = "Sword Arm of Dragon",
  SwampBattleguard = "Swamp Battleguard",
  TheSternMystic = "The Stern Mystic",
  BattleSteer = "Battle Steer",
  FlameSwordsman = "Flame Swordsman",
  TimeWizard = "Time Wizard",
  RightLegOfTheForbiddenOne = "Right Leg of the Forbidden One",
  LeftLegOfTheForbiddenOne = "Left Leg of the Forbidden One",
  RightArmOfTheForbiddenOne = "Right Arm of the Forbidden One",
  LeftArmOfTheForbiddenOne = "Left Arm of the Forbidden One",
  ExodiaTheForbiddenOne = "Exodia the Forbidden One",
  SummonedSkull = "Summoned Skull",
  TheWickedWormBeast = "The Wicked Worm Beast",
  SkullServant = "Skull Servant",
  HornImp = "Horn Imp",
  BattleOx = "Battle Ox",
  BeaverWarrior = "Beaver Warrior",
  RockOgreGrotto1 = "Rock Ogre Grotto #1",
  MountainWarrior = "Mountain Warrior",
  ZombieWarrior = "Zombie Warrior",
  KoumoriDragon = "Koumori Dragon",
  TwoHeadedKingRex = "Two-Headed King Rex",
  JudgeMan = "Judge Man",
  SaggiTheDarkClown = "Saggi the Dark Clown",
  DarkMagician = "Dark Magician",
  TheSnakeHair = "The Snake Hair",
  GaiaTheDragonChampion = "Gaia the Dragon Champion",
  GaiaTheFierceKnight = "Gaia The Fierce Knight",
  CurseOfDragon = "Curse of Dragon",
  DragonPiper = "Dragon Piper",
  CelticGuardian = "Celtic Guardian",
  IllusionistFacelessMage = "Illusionist Faceless Mage",
  KarbonalaWarrior = "Karbonala Warrior",
  RogueDoll = "Rogue Doll",
  OscilloHero2 = "Oscillo Hero #2",
  Griffore = "Griffore",
  Torike = "Torike",
  Sangan = "Sangan",
  BigInsect = "Big Insect",
  BasicInsect = "Basic Insect",
  ArmoredLizard = "Armored Lizard",
  HerculesBeetle = "Hercules Beetle",
  KillerNeedle = "Killer Needle",
  Gokibore = "Gokibore",
  GiantFlea = "Giant Flea",
  LarvaeMoth = "Larvae Moth",
  GreatMoth = "Great Moth",
  Kuriboh = "Kuriboh",
  MammothGraveyard = "Mammoth Graveyard",
  GreatWhite = "Great White",
  Wolf = "Wolf",
  HarpieLady = "Harpie Lady",
  HarpieLadySisters = "Harpie Lady Sisters",
  TigerAxe = "Tiger Axe",
  SilverFang = "Silver Fang",
  Kojikocy = "Kojikocy",
  PerfectlyUltimateGreatMoth = "Perfectly Ultimate Great Moth",
  Garoozis = "Garoozis",
  ThousandDragon = "Thousand Dragon",
  FiendKraken = "Fiend Kraken",
  Jellyfish = "Jellyfish",
  CocoonOfEvolution = "Cocoon of Evolution",
  KairyuShin = "Kairyu-Shin",
  GiantSoldierOfStone = "Giant Soldier of Stone",
  ManEatingPlant = "Man-Eating Plant",
  Krokodilus = "Krokodilus",
  Grappler = "Grappler",
  AxeRaider = "Axe Raider",
  Megazowler = "Megazowler",
  Uraby = "Uraby",
  CrawlingDragon2 = "Crawling Dragon #2",
  RedEyesBDragon = "Red-Eyes B. Dragon",
  CastleOfDarkIllusions = "Castle of Dark Illusions",
  ReaperOfTheCards = "Reaper of the Cards",
  KingOfYamimakai = "King of Yamimakai",
  Barox = "Barox",
  DarkChimera = "Dark Chimera",
  MetalGuardian = "Metal Guardian",
  CatapultTurtle = "Catapult Turtle",
  GyakutennoMegami = "Gyakutenno Megami",
  MysticHorseman = "Mystic Horseman",
  RabidHorseman = "Rabid Horseman",
  Zanki = "Zanki",
  CrawlingDragon = "Crawling Dragon",
  CrassClown = "Crass Clown",
  ArmoredZombie = "Armored Zombie",
  DragonZombie = "Dragon Zombie",
  ClownZombie = "Clown Zombie",
  PumpkingTheKingOfGhosts = "Pumpking the King of Ghosts",
  BattleWarrior = "Battle Warrior",
  WingsOfWickedFlame = "Wings of Wicked Flame",
  MaskOfDarkness = "Mask of Darkness",
  BaronOfTheFiendSword = "Baron of the Fiend Sword",
  CurtainOfTheDarkOnes = "Curtain of the Dark Ones",
  Tomozaurus = "Tomozaurus",
  SpiritOfTheWinds = "Spirit of the Winds",
  ShiningAbyss = "Shining Abyss",
  HeadlessKnight = "Headless Knight",
  GoddesswithTheThirdEye = "Goddess with the Third Eye",
  RuklambaTheSpiritKing = "Ruklamba the Spirit King",
  DomaTheAngelOfSilence = "Doma The Angel of Silence",
  Keldo = "Keldo",
  SoldierAri = "Soldier Ari",
  WhiteMagicalHat = "White Magical Hat",
  GearfriedTheIronKnight = "Gearfried the Iron Knight",
  NightmareScorpion = "Nightmare Scorpion",
  SpiritOfTheBooks = "Spirit of the Books",
  XYZDragonCannon = "XYZ-Dragon Cannon",
  HumanoidSlime = "Humanoid Slime",
  DreamClown = "Dream Clown",
  SleepingLion = "Sleeping Lion",
  YamatanoDragonScroll = "Yamatano Dragon Scroll",
  DarkPlant = "Dark Plant",
  WormDrake = "Worm Drake",
  FaithBird = "Faith Bird",
  OrionTheBattleKing = "Orion the Battle King",
  Ansatsu = "Ansatsu",
  LaMoon = "LaMoon",
  Nemuriko = "Nemuriko",
  WeatherControl = "Weather Control",
  Octoberser = "Octoberser",
  HumanoidWormDrake = "Humanoid Worm Drake",
  CharubinTheFireKnight = "Charubin the Fire Knight",
  RevivalJam = "Revival Jam",
  FiendsHand = "Fiend's Hand",
  WittyPhantom = "Witty Phantom",
  BusterBlader = "Buster Blader",
  DarkNecrofear = "Dark Necrofear",
  BlueEyedSilverZombie = "Blue-Eyed Silver Zombie",
  ToadMaster = "Toad Master",
  SpikedSnail = "Spiked Snail",
  FlameManipulator = "Flame Manipulator",
  NecrolancerTheTimelord = "Necrolancer the Timelord",
  DjinnTheWatcherOfTheWind = "Djinn the Watcher of the Wind",
  TheBewitchingPhantomThief = "The Bewitching Phantom Thief",
  TempleOfSkulls = "Temple of Skulls",
  MonsterEgg = "Monster Egg",
  TheShadowWhoControlsTheDark = "The Shadow Who Controls the Dark",
  XHeadCannon = "X-Head Cannon",
  Akihiron = "Akihiron",
  OrgothTheRelentless = "Orgoth the Relentless",
  TheMeltingRedShadow = "The Melting Red Shadow",
  DokuroizoTheGrimReaper = "Dokuroizo the Grim Reaper",
  FireReaper = "Fire Reaper",
  Larvas = "Larvas",
  HardArmor = "Hard Armor",
  Firegrass = "Firegrass",
  CyberJar = "Cyber Jar",
  DigBeak = "Dig Beak",
  MWarrior1 = "M-Warrior #1",
  MWarrior2 = "M-Warrior #2",
  BanisherOfTheLight = "Banisher of the Light",
  Lisark = "Lisark",
  DesFeralImp = "Des Feral Imp",
  TheJudgementHand = "The Judgement Hand",
  MysteriousPuppeteer = "Mysterious Puppeteer",
  AncientJar = "Ancient Jar",
  DarkfireDragon = "Darkfire Dragon",
  DarkKingOfTheAbyss = "Dark King of the Abyss",
  SpiritOfTheHarp = "Spirit of the Harp",
  BigEye = "Big Eye",
  Armaill = "Armaill",
  GiantRat = "Giant Rat",
  SenjuOfTheThousandHands = "Senju of the Thousand Hands",
  UFOTurtle = "UFO Turtle",
  FireEye = "Fire Eye",
  Monsturtle = "Monsturtle",
  ClawReacher = "Claw Reacher",
  PhantomDewan = "Phantom Dewan",
  Arlownay = "Arlownay",
  FlashAssailant = "Flash Assailant",
  KarateMan = "Karate Man",
  LuckyTrinket = "Lucky Trinket",
  Genin = "Genin",
  DarkZebra = "Dark Zebra",
  FiendReflection2 = "Fiend Reflection #2",
  GateDeeg = "Gate Deeg",
  GiantGerm = "Giant Germ",
  Fusionist = "Fusionist",
  NimbleMomonga = "Nimble Momonga",
  LaLaLioon = "LaLa Li-oon",
  KeyMace = "Key Mace",
  Doron = "Doron",
  BoarSoldier = "Boar Soldier",
  HappyLover = "Happy Lover",
  PenguinKnight = "Penguin Knight",
  PetitDragon = "Petit Dragon",
  FrenziedPanda = "Frenzied Panda",
  AirMarmotOfNefariousness = "Air Marmot of Nefariousness",
  PhantomGhost = "Phantom Ghost",
  MotherGrizzly = "Mother Grizzly",
  FlyingKamakiri1 = "Flying Kamakiri #1",
  TwinLongRods1 = "Twin Long Rods #1",
  DrollBird = "Droll Bird",
  PetitAngel = "Petit Angel",
  WingedCleaver = "Winged Cleaver",
  HinotamaSoul = "Hinotama Soul",
  Kaminarikozou = "Kaminarikozou",
  Meotoko = "Meotoko",
  AquaMadoor = "Aqua Madoor",
  KagemushaOfTheBlueFlame = "Kagemusha of the Blue Flame",
  FlameGhost = "Flame Ghost",
  NightmarePenguin = "Nightmare Penguin",
  BSkullDragon = "B. Skull Dragon",
  TwoMouthDarkruler = "Two-Mouth Darkruler",
  Solitude = "Solitude",
  MaskedSorcerer = "Masked Sorcerer",
  Kumootoko = "Kumootoko",
  CeremonialBell = "Ceremonial Bell",
  RoaringOceanSnake = "Roaring Ocean Snake",
  TrapMaster = "Trap Master",
  FiendSword = "Fiend Sword",
  SonicBird = "Sonic Bird",
  MysticTomato = "Mystic Tomato",
  WoodRemains = "Wood Remains",
  HourglassOfLife = "Hourglass of Life",
  RareFish = "Rare Fish",
  WoodClown = "Wood Clown",
  Kotodama = "Kotodama",
  ObeliskTheTormentor = "Obelisk the Tormentor",
  WodanTheResidentOfTheForest = "Wodan the Resident of the Forest",
  PerfectMachineKing = "Perfect Machine King",
  Haniwa = "Haniwa",
  SliferTheSkyDragon = "Slifer the Sky Dragon",
  VishwarRandi = "Vishwar Randi",
  TheWingedDragonOfRaBattleMode = "The Winged Dragon of Ra (Battle Mode)",
  DarkAssailant = "Dark Assailant",
  CandleOfFate = "Candle of Fate",
  WaterElement = "Water Element",
  Dissolverock = "Dissolverock",
  FlyingFish = "Flying Fish",
  OneWhoHuntsSouls = "One Who Hunts Souls",
  RootWater = "Root Water",
  AmphibianBeast = "Amphibian Beast",
  WaterOmotics = "Water Omotics",
  AlligatorsSwordDragon = "Alligator's Sword Dragon",
  EnchantingMermaid = "Enchanting Mermaid",
  Nekogal1 = "Nekogal #1",
  RocketWarrior = "Rocket Warrior",
  AquaSerpent = "Aqua Serpent",
  PreventRat = "Prevent Rat",
  DimensionalWarrior = "Dimensional Warrior",
  TheLegendaryFisherman = "The Legendary Fisherman",
  BeastkingOfTheSwamps = "Beastking of the Swamps",
  SatelliteCannon = "Satellite Cannon",
  LunarQueenElzaim = "Lunar Queen Elzaim",
  WickedMirror = "Wicked Mirror",
  TheLittleSwordsmanOfAile = "The Little Swordsman of Aile",
  RockOgreGrotto2 = "Rock Ogre Grotto #2",
  WingEggElf = "Wing Egg Elf",
  TheFuriousSeaKing = "The Furious Sea King",
  PrincessOfTsurugi = "Princess of Tsurugi",
  MorphingJar2 = "Morphing Jar #2",
  VorseRaider = "Vorse Raider",
  VersagoTheDestroyer = "Versago the Destroyer",
  Wetha = "Wetha",
  MegirusLight = "Megirus Light",
  Mavelus = "Mavelus",
  AncientTreeOfEnlightenment = "Ancient Tree of Enlightenment",
  GreenPhantomKing = "Green Phantom King",
  GroundAttackerBugroth = "Ground Attacker Bugroth",
  RayTemperature = "Ray & Temperature",
  FlameChampion = "Flame Champion",
  PetitMoth = "Petit Moth",
  TwinHeadedFireDragon = "Twin-Headed Fire Dragon",
  DarkfireSoldier1 = "Darkfire Soldier #1",
  MysticClown = "Mystic Clown",
  MysticalSheep2 = "Mystical Sheep #2",
  Holograh = "Holograh",
  TaoTheChanter = "Tao the Chanter",
  SerpentMarauder = "Serpent Marauder",
  MrVolcano = "Mr. Volcano",
  OgreOfTheBlackShadow = "Ogre of the Black Shadow",
  DarkfireSoldier2 = "Darkfire Soldier #2",
  ChangeSlime = "Change Slime",
  MoonEnvoy = "Moon Envoy",
  Fireyarou = "Fireyarou",
  Kiseitai = "Kiseitai",
  MasakiTheLegendarySwordsman = "Masaki the Legendary Swordsman",
  DragonessTheWickedKnight = "Dragoness the Wicked Knight",
  CyberFalcon = "Cyber Falcon",
  OneEyedShieldDragon = "One-Eyed Shield Dragon",
  TheWingedDragonOfRaSphereMode = "The Winged Dragon of Ra (Sphere Mode)",
  WickedDragonwithTheErsatzHead = "Wicked Dragon with the Ersatz Head",
  SonicMaid = "Sonic Maid",
  Kurama = "Kurama",
  Yaranzo = "Yaranzo",
  KananTheSwordmistress = "Kanan the Swordmistress",
  Takriminos = "Takriminos",
  StuffedAnimal = "Stuffed Animal",
  MegasonicEye = "Megasonic Eye",
  SuperWarLion = "Super War-Lion",
  Yamadron = "Yamadron",
  Seiyaryu = "Seiyaryu",
  ThreeLeggedZombies = "Three-Legged Zombies",
  ZeraTheMant = "Zera The Mant",
  FlyingPenguin = "Flying Penguin",
  MillenniumShield = "Millennium Shield",
  FairysGift = "Fairy's Gift",
  BlackLusterSoldier = "Black Luster Soldier",
  FiendsMirror = "Fiend's Mirror",
  LabyrinthWall = "Labyrinth Wall",
  JiraiGumo = "Jirai Gumo",
  ShadowGhoul = "Shadow Ghoul",
  WallShadow = "Wall Shadow",
  LabyrinthTank = "Labyrinth Tank",
  SangaOfTheThunder = "Sanga of the Thunder",
  Kazejin = "Kazejin",
  Suijin = "Suijin",
  GateGuardian = "Gate Guardian",
  DungeonWorm = "Dungeon Worm",
  MonsterTamer = "Monster Tamer",
  RyuKishinPowered = "Ryu-Kishin Powered",
  Swordstalker = "Swordstalker",
  LaJinnTheMysticalGenieOfTheLamp = "La Jinn the Mystical Genie of the Lamp",
  BlueEyesUltimateDragon = "Blue-Eyes Ultimate Dragon",
  ToonAlligator = "Toon Alligator",
  RudeKaiser = "Rude Kaiser",
  ParrotDragon = "Parrot Dragon",
  DarkRabbit = "Dark Rabbit",
  Bickuribox = "Bickuribox",
  HarpiesPetDragon = "Harpie's Pet Dragon",
  MysticLamp = "Mystic Lamp",
  PendulumMachine = "Pendulum Machine",
  GiltiaTheDKnight = "Giltia the D. Knight",
  LauncherSpider = "Launcher Spider",
  Zoa = "Zoa",
  Metalzoa = "Metalzoa",
  ZoneEater = "Zone Eater",
  SteelScorpion = "Steel Scorpion",
  DancingElf = "Dancing Elf",
  Ocubeam = "Ocubeam",
  Leghul = "Leghul",
  Ooguchi = "Ooguchi",
  GammaTheMagnetWarrior = "Gamma The Magnet Warrior",
  EmperorOfTheLandandSea = "Emperor of the Land and Sea",
  UshiOni = "Ushi Oni",
  MonsterEye = "Monster Eye",
  Leogun = "Leogun",
  Tatsunootoshigo = "Tatsunootoshigo",
  SaberSlasher = "Saber Slasher",
  KaiserSeaHorse = "Kaiser Sea Horse",
  MachineKing = "Machine King",
  GiantMechSoldier = "Giant Mech-Soldier",
  MetalDragon = "Metal Dragon",
  MechanicalSpider = "Mechanical Spider",
  Bat = "Bat",
  TheWingedDragonOfRaPhoenixMode = "The Winged Dragon of Ra (Phoenix Mode)",
  CyberSoldier = "Cyber Soldier",
  ShovelCrusher = "Shovel Crusher",
  Mechanicalchaser = "Mechanicalchaser",
  Blocker = "Blocker",
  BlastJuggler = "Blast Juggler",
  Golgoil = "Golgoil",
  FlyingKamakiri2 = "Flying Kamakiri #2",
  CyberStein = "Cyber-Stein",
  CyberCommander = "Cyber Commander",
  Jinzo7 = "Jinzo #7",
  DiceArmadillo = "Dice Armadillo",
  SkyDragon = "Sky Dragon",
  ThunderDragon = "Thunder Dragon",
  StoneD = "Stone D.",
  KaiserDragon = "Kaiser Dragon",
  MagicianOfFaith = "Magician of Faith",
  GoddessOfWhim = "Goddess of Whim",
  Gradius = "Gradius",
  IceWater = "Ice Water",
  WaterdragonFairy = "Waterdragon Fairy",
  AncientElf = "Ancient Elf",
  HarpiesBrother = "Harpie's Brother",
  Aeris = "Aeris",
  WhiteDolphin = "White Dolphin",
  DeepseaShark = "Deepsea Shark",
  MetalFish = "Metal Fish",
  GrandTikiElder = "Grand Tiki Elder",
  _7ColoredFish = "7 Colored Fish",
  MechBass = "Mech Bass",
  AquaDragon = "Aqua Dragon",
  SeaKingDragon = "Sea King Dragon",
  TuruPurun = "Turu-Purun",
  GiantRex = "Giant Rex",
  AquaSnake = "Aqua Snake",
  GiantRedSeasnake = "Giant Red Seasnake",
  SpikeSeadra = "Spike Seadra",
  _30000YearWhiteTurtle = "30,000-Year White Turtle",
  KappaAvenger = "Kappa Avenger",
  Kanikabuto = "Kanikabuto",
  Zarigun = "Zarigun",
  MillenniumGolem = "Millennium Golem",
  DestroyerGolem = "Destroyer Golem",
  BarrelRock = "Barrel Rock",
  MinomushiWarrior = "Minomushi Warrior",
  TheMaskedBeast = "The Masked Beast",
  KaminariAttack = "Kaminari Attack",
  TripwireBeast = "Tripwire Beast",
  BoltEscargot = "Bolt Escargot",
  BoltPenguin = "Bolt Penguin",
  TheImmortalOfThunder = "The Immortal of Thunder",
  ElectricSnake = "Electric Snake",
  WingEagle = "Wing Eagle",
  PunishedEagle = "Punished Eagle",
  SkullRedBird = "Skull Red Bird",
  CrimsonSunbird = "Crimson Sunbird",
  QueenBird = "Queen Bird",
  ArmedNinja = "Armed Ninja",
  MagicalGhost = "Magical Ghost",
  SoulHunter = "Soul Hunter",
  TheEarlOfDemise = "The Earl of Demise",
  VermillionSparrow = "Vermillion Sparrow",
  SeaKamen = "Sea Kamen",
  SinisterSerpent = "Sinister Serpent",
  Ganigumo = "Ganigumo",
  Alinsection = "Alinsection",
  InsectSoldiersOfTheSky = "Insect Soldiers of the Sky",
  CockroachKnight = "Cockroach Knight",
  KuwagataA = "Kuwagata A",
  Burglar = "Burglar",
  Pragtical = "Pragtical",
  Garvas = "Garvas",
  Ameba = "Ameba",
  Korogashi = "Korogashi",
  BooKoo = "Boo Koo",
  FlowerWolf = "Flower Wolf",
  RainbowFlower = "Rainbow Flower",
  BarrelLily = "Barrel Lily",
  NeedleBall = "Needle Ball",
  Peacock = "Peacock",
  Hoshiningen = "Hoshiningen",
  MahaVailo = "Maha Vailo",
  RainbowMarineMermaid = "Rainbow Marine Mermaid",
  MusicianKing = "Musician King",
  Wilmee = "Wilmee",
  YadoKaru = "Yado Karu",
  Morinphen = "Morinphen",
  Boneheimer = "Boneheimer",
  DragonSeeker = "Dragon Seeker",
  ManEaterBug = "Man-Eater Bug",
  PenguinTorpedo = "Penguin Torpedo",
  TurtleRaccoon = "Turtle Raccoon",
  FlameDancer = "Flame Dancer",
  Prisman = "Prisman",
  GaleDogra = "Gale Dogra",
  CrazyFish = "Crazy Fish",
  CyberSaurus = "Cyber Saurus",
  Bracchioraidus = "Bracchio-raidus",
  LaughingFlower = "Laughing Flower",
  BeanSoldier = "Bean Soldier",
  CannonSoldier = "Cannon Soldier",
  GuardianOfTheThroneRoom = "Guardian of the Throne Room",
  AsuraPriest = "Asura Priest",
  TheStatueOfEasterIsland = "The Statue of Easter Island",
  MukaMuka = "Muka Muka",
  ZombyraTheDark = "Zombyra the Dark",
  BoulderTortoise = "Boulder Tortoise",
  FireKraken = "Fire Kraken",
  TurtleBird = "Turtle Bird",
  Skullbird = "Skullbird",
  MonstrousBird = "Monstrous Bird",
  TheBistroButcher = "The Bistro Butcher",
  StarBoy = "Star Boy",
  SpiritOfTheMountain = "Spirit of the Mountain",
  EarthboundSpirit = "Earthbound Spirit",
  MilusRadiant = "Milus Radiant",
  Togex = "Togex",
  FlameCerebrus = "Flame Cerebrus",
  EmbodimentOfApophis = "Embodiment of Apophis",
  MysticalSand = "Mystical Sand",
  GeminiElf = "Gemini Elf",
  KwagarHercules = "Kwagar Hercules",
  Minar = "Minar",
  AncientLamp = "Ancient Lamp",
  Mechaleon = "Mechaleon",
  MegaThunderball = "Mega Thunderball",
  Niwatori = "Niwatori",
  AmazonChainMaster = "Amazon Chain Master",
  Skelengel = "Skelengel",
  HaneHane = "Hane-Hane",
  Misairuzame = "Misairuzame",
  ThunderNyanNyan = "Thunder Nyan Nyan",
  DharmaCannon = "Dharma Cannon",
  Skelgon = "Skelgon",
  WowWarrior = "Wow Warrior",
  Griggle = "Griggle",
  BoneMouse = "Bone Mouse",
  FrogTheJam = "Frog the Jam",
  LastTuskMammoth = "Last Tusk Mammoth",
  DarkElf = "Dark Elf",
  WingedDragonGuardianOfTheFortress2 = "Winged Dragon, Guardian of the Fortress #2",
  MushroomMan2 = "Mushroom Man #2",
  LavaBattleguard = "Lava Battleguard",
  QueensKnight = "Queen's Knight",
  InjectionFairyLily = "Injection Fairy Lily",
  JacksKnight = "Jack's Knight",
  PotTheTrick = "Pot the Trick",
  OscilloHero = "Oscillo Hero",
  InvaderFromAnotherDimension = "Invader from Another Dimension",
  LesserDragon = "Lesser Dragon",
  NeedleWorm = "Needle Worm",
  KingsKnight = "King's Knight",
  GreatMammothOfGoldfine = "Great Mammoth of Goldfine",
  GilGarth = "Gil Garth",
  Yormungarde = "Yormungarde",
  DarkworldThorns = "Darkworld Thorns",
  BladeKnight = "Blade Knight",
  Gernia = "Gernia",
  Trakadon = "Trakadon",
  BDragonJungleKing = "B. Dragon Jungle King",
  EmpressJudge = "Empress Judge",
  LittleD = "Little D",
  WitchOfTheBlackForest = "Witch of the Black Forest",
  YDragonHead = "Y-Dragon Head",
  GiantScorpionOfTheTundra = "Giant Scorpion of the Tundra",
  CrowGoblin = "Crow Goblin",
  DarkMagicianKnight = "Dark Magician Knight",
  AbyssFlower = "Abyss Flower",
  PatrolRobo = "Patrol Robo",
  Takuhee = "Takuhee",
  DarkWitch = "Dark Witch",
  LivingVase = "Living Vase",
  TentaclePlant = "Tentacle Plant",
  ZMetalTank = "Z-Metal Tank",
  MorphingJar = "Morphing Jar",
  MuseA = "Muse-A",
  XYDragonCannon = "XY-Dragon Cannon",
  RoseSpectreOfDunn = "Rose Spectre of Dunn",
  FiendReflection1 = "Fiend Reflection #1",
  XZTankCannon = "XZ-Tank Cannon",
  YZTankDragon = "YZ-Tank Dragon",
  LittleChimera = "Little Chimera",
  ViolentRain = "Violent Rain",
  ExodiaNecross = "Exodia Necross",
  PenguinSoldier = "Penguin Soldier",
  FairyDragon = "Fairy Dragon",
  Helpoemer = "Helpoemer",
  LavaGolem = "Lava Golem",
  Newdoria = "Newdoria",
  DarkJeroid = "Dark Jeroid",
  ShiningFriendship = "Shining Friendship",
  ElectricLizard = "Electric Lizard",
  HirosShadowScout = "Hiro's Shadow Scout",
  LadyOfFaith = "Lady of Faith",
  TwinHeadedThunderDragon = "Twin-Headed Thunder Dragon",
  HunterSpider = "Hunter Spider",
  ArmoredStarfish = "Armored Starfish",
  ExecutorMakyura = "Executor - Makyura",
  MarineBeast = "Marine Beast",
  WarriorOfTradition = "Warrior of Tradition",
  ByserShock = "Byser Shock",
  Snakeyashi = "Snakeyashi",
  SuccubusKnight = "Succubus Knight",
  IllWitch = "Ill Witch",
  ViserDes = "Viser Des",
  HighTideGyojin = "High Tide Gyojin",
  FairyOfTheFountain = "Fairy of the Fountain",
  AmazonOfTheSeas = "Amazon of the Seas",
  Nekogal2 = "Nekogal #2",
  WitchsApprentice = "Witch's Apprentice",
  PuppetMaster = "Puppet Master",
  AmazonFighter = "Amazon Fighter",
  MaidenOfTheMoonlight = "Maiden of the Moonlight",
  StoneOgreGrotto = "Stone Ogre Grotto",
  AmazonSwordWoman = "Amazon Sword Woman",
  VampireLord = "Vampire Lord",
  QueensDouble = "Queen's Double",
  DarkPaladin = "Dark Paladin",
  Trent = "Trent",
  QueenOfAutumnLeaves = "Queen of Autumn Leaves",
  AmphibiousBugroth = "Amphibious Bugroth",
  DifferentDimensionDragon = "Different Dimension Dragon",
  MysticalSheep1 = "Mystical Sheep #1",
  YamataDragon = "Yamata Dragon",
  ShinatoKingOfAHigherPlane = "Shinato, King of a Higher Plane",
  DarkFlareKnight = "Dark Flare Knight",
  MirageKnight = "Mirage Knight",
  BerserkDragon = "Berserk Dragon",
  MachineAttacker = "Machine Attacker",
  CommandAngel = "Command Angel",
  WhiptailCrow = "Whiptail Crow",
  DesVolstgalph = "Des Volstgalph",
  ToonDarkMagicianGirl = "Toon Dark Magician Girl",
  GilfordTheLightning = "Gilford the Lightning",
  MysticalBeastSerket = "Mystical Beast Serket",
  CyberHarpie = "Cyber Harpie",
  LightningConger = "Lightning Conger",
  ExarionUniverse = "Exarion Universe",
  LegendaryFiend = "Legendary Fiend",
  GadgetSoldier = "Gadget Soldier",
  MelchidTheFourFaceBeast = "Melchid the Four-Face Beast",
  NuviaTheWicked = "Nuvia the Wicked",
  MaskedBeastDesGardius = "Masked Beast Des Gardius",
  ValkyrionTheMagnaWarrior = "Valkyrion the Magna Warrior",
  DarkSage = "Dark Sage",
  FGD = "F.G.D.",
  MasterOfDragonSoldier = "Master of Dragon Soldier",
  PerformanceOfSword = "Performance of Sword",
  HungryBurger = "Hungry Burger",
  Sengenjin = "Sengenjin",
  SkullGuardian = "Skull Guardian",
  TriHornedDragon = "Tri-Horned Dragon",
  SerpentNightDragon = "Serpent Night Dragon",
  SkullKnight = "Skull Knight",
  CosmoQueen = "Cosmo Queen",
  Chakra = "Chakra",
  CrabTurtle = "Crab Turtle",
  Mikazukinoyaiba = "Mikazukinoyaiba",
  MeteorDragon = "Meteor Dragon",
  MeteorBDragon = "Meteor B. Dragon",
  FirewingPegasus = "Firewing Pegasus",
  PsychoPuppet = "Psycho-Puppet",
  GarmaSword = "Garma Sword",
  JavelinBeetle = "Javelin Beetle",
  FortressWhale = "Fortress Whale",
  Dokurorider = "Dokurorider",
  MaskOfShineDark = "Mask of Shine & Dark",
  MagicianOfBlackChaos = "Magician of Black Chaos",
  SlotMachine = "Slot Machine",
  SpaceMegatron = "Space Megatron",
  RedArcheryGirl = "Red Archery Girl",
  RyuRan = "Ryu-Ran",
  MangaRyuRan = "Manga Ryu-Ran",
  ToonMermaid = "Toon Mermaid",
  ToonSummonedSkull = "Toon Summoned Skull",
  DarkEyesIllusionist = "Dark-Eyes Illusionist",
  Relinquished = "Relinquished",
  JigenBakudan = "Jigen Bakudan",
  ThousandEyesIdol = "Thousand-Eyes Idol",
  ThousandEyesRestrict = "Thousand-Eyes Restrict",
  SteelOgreGrotto2 = "Steel Ogre Grotto #2",
  BlastSphere = "Blast Sphere",
  Hyozanryu = "Hyozanryu",
  AlphaTheMagnetWarrior = "Alpha The Magnet Warrior",
  LegionTheFiendJester = "Legion the Fiend Jester",
  InvitationToADarkSleep = "Invitation to a Dark Sleep",
  LordOfD = "Lord of D.",
  RedEyesBlackMetalDragon = "Red-Eyes Black Metal Dragon",
  BarrelDragon = "Barrel Dragon",
  HannibalNecromancer = "Hannibal Necromancer",
  PantherWarrior = "Panther Warrior",
  ThreeHeadedGeedo = "Three-Headed Geedo",
  GazelleTheKingOfMythicalBeasts = "Gazelle the King of Mythical Beasts",
  StoneStatueOfTheAztecs = "Stone Statue of the Aztecs",
  Berfomet = "Berfomet",
  ChimeraTheFlyingMythicalBeast = "Chimera the Flying Mythical Beast",
  GearGolemTheMovingFortress = "Gear Golem the Moving Fortress",
  Jinzo = "Jinzo",
  SwordsmanOfLandstar = "Swordsman of Landstar",
  CyberRaider = "Cyber Raider",
  TheFiendMegacyber = "The Fiend Megacyber",
  ReflectBounder = "Reflect Bounder",
  BetaTheMagnetWarrior = "Beta The Magnet Warrior",
  BigShieldGardna = "Big Shield Gardna",
  DollOfDemise = "Doll of Demise",
  DarkMagicianGirl = "Dark Magician Girl",
  AlligatorsSword = "Alligator's Sword",
  InsectQueen = "Insect Queen",
  ParasiteParacide = "Parasite Paracide",
  SkullMarkLadyBug = "Skull-Mark Lady Bug",
  TinyGuardian = "Tiny Guardian",
  PinchHopper = "Pinch Hopper",
  BlueEyesToonDragon = "Blue-Eyes Toon Dragon",
  TheUnhappyMaiden = "The Unhappy Maiden",
  WallOfIllusion = "Wall of Illusion",
  NeoTheMagicSwordsman = "Neo the Magic Swordsman",
  ManEatingTreasureChest = "Man-Eating Treasure Chest",
  ChironTheMage = "Chiron the Mage",
  SwordHunter = "Sword Hunter",
  DrillBug = "Drill Bug",
  DeepseaWarrior = "Deepsea Warrior",
  BiteShoes = "Bite Shoes",
  Spikebot = "Spikebot",
  BeastOfGilfer = "Beast of Gilfer",
  ThePortraitsSecret = "The Portrait's Secret",
  TheGrossGhostOfFledDreams = "The Gross Ghost of Fled Dreams",
  GateSword = "Gate Sword",
  SteelFanFighter = "Steel Fan Fighter",
  LeopardGirl = "Leopard Girl",
  TheLastWarriorFromAnotherPlanet = "The Last Warrior from Another Planet",
  DunamesDarkWitch = "Dunames Dark Witch",
  GarneciaElefantis = "Garnecia Elefantis",
  TotalDefenseShogun = "Total Defense Shogun",
  BeastOfTalwar = "Beast of Talwar",
  CyberTechAlligator = "Cyber-Tech Alligator",
  TalonsOfShurilane = "Talons of Shurilane",
}

export type GraveyardEffectMonster = Extract<
  Monster,
  | Monster.TheWingedDragonOfRaPhoenixMode
  | Monster.Helpoemer
  | Monster.Newdoria
  | Monster.VampireLord
  | Monster.DifferentDimensionDragon
  | Monster.DarkFlareKnight
>;

export type HandEffectMonster = Extract<Monster, Monster.LavaGolem>;

export type FlipEffectMonster = Extract<
  Monster,
  | Monster.MysticalElf
  | Monster.FlameSwordsman
  | Monster.TimeWizard
  | Monster.BattleOx
  | Monster.CurseOfDragon
  | Monster.IllusionistFacelessMage
  | Monster.HarpieLady
  | Monster.HarpieLadySisters
  | Monster.KairyuShin
  | Monster.GiantSoldierOfStone
  | Monster.ReaperOfTheCards
  | Monster.CatapultTurtle
  | Monster.GyakutennoMegami
  | Monster.SpiritOfTheBooks
  | Monster.XYZDragonCannon
  | Monster.Nemuriko
  | Monster.RevivalJam
  | Monster.FiendsHand
  | Monster.DarkNecrofear
  | Monster.ToadMaster
  | Monster.XHeadCannon
  | Monster.FireReaper
  | Monster.Doron
  | Monster.TrapMaster
  | Monster.HourglassOfLife
  | Monster.ObeliskTheTormentor
  | Monster.TheWingedDragonOfRaBattleMode
  | Monster.RocketWarrior
  | Monster.BeastkingOfTheSwamps
  | Monster.FairysGift
  | Monster.MonsterTamer
  | Monster.MysticLamp
  | Monster.Leghul
  | Monster.GammaTheMagnetWarrior
  | Monster.MonsterEye
  | Monster.TheWingedDragonOfRaPhoenixMode
  | Monster.GoddessOfWhim
  | Monster.DragonSeeker
  | Monster.PenguinTorpedo
  | Monster.ZombyraTheDark
  | Monster.SpiritOfTheMountain
  | Monster.AncientLamp
  | Monster.Skelengel
  | Monster.KingsKnight
  | Monster.YDragonHead
  | Monster.ZMetalTank
  | Monster.XYDragonCannon
  | Monster.XZTankCannon
  | Monster.YZTankDragon
  | Monster.ElectricLizard
  | Monster.LadyOfFaith
  | Monster.ByserShock
  | Monster.PuppetMaster
  | Monster.DarkPaladin
  | Monster.Trent
  | Monster.BerserkDragon
  | Monster.DesVolstgalph
  | Monster.GilfordTheLightning
  | Monster.MysticalBeastSerket
  | Monster.CyberHarpie
  | Monster.ExarionUniverse
  | Monster.LegendaryFiend
  | Monster.ValkyrionTheMagnaWarrior
  | Monster.FGD
  | Monster.RedArcheryGirl
  | Monster.Relinquished
  | Monster.ThousandEyesRestrict
  | Monster.AlphaTheMagnetWarrior
  | Monster.InvitationToADarkSleep
  | Monster.BarrelDragon
  | Monster.ReflectBounder
  | Monster.BetaTheMagnetWarrior
  | Monster.ParasiteParacide
  | Monster.SkullMarkLadyBug
  | Monster.PinchHopper
  | Monster.ChironTheMage
  | Monster.BeastOfGilfer
>;

export type PermAutoEffectMonster = Extract<
  Monster,
  | Monster.CastleOfDarkIllusions
  | Monster.SatelliteCannon
  | Monster.ThunderNyanNyan
  | Monster.ExodiaNecross
  | Monster.LavaGolem
  | Monster.ViserDes
  | Monster.MirageKnight
  | Monster.BerserkDragon
  | Monster.Jinzo
  | Monster.PetitMoth
  | Monster.CocoonOfEvolution
  | Monster.GreatMoth
>;

export type TempPowerUpMonster = Extract<
  Monster,
  | Monster.SwampBattleguard
  | Monster.MammothGraveyard
  | Monster.PumpkingTheKingOfGhosts
  | Monster.BusterBlader
  | Monster.MWarrior1
  | Monster.MWarrior2
  | Monster.NightmarePenguin
  | Monster.WodanTheResidentOfTheForest
  | Monster.PerfectMachineKing
  | Monster.SliferTheSkyDragon
  | Monster.LabyrinthTank
  | Monster.MachineKing
  | Monster.Hoshiningen
  | Monster.LavaBattleguard
  | Monster.BladeKnight
  | Monster.DarkJeroid
  | Monster.WitchsApprentice
  | Monster.CommandAngel
  | Monster.ToonDarkMagicianGirl
  | Monster.MasterOfDragonSoldier
  | Monster.DarkMagicianGirl
  | Monster.InsectQueen
>;

export enum Spell {
  // burn
  Sparks = "Sparks",
  Hinotama = "Hinotama",
  FinalFlame = "Final Flame",
  Ookazi = "Ookazi",
  TremendousFire = "Tremendous Fire",
  RestructerRevolution = "Restructer Revolution",

  // heal
  MooyanCurry = "Mooyan Curry",
  RedMedicine = "Red Medicine",
  GoblinsSecretRemedy = "Goblin's Secret Remedy",
  SoulOfThePure = "Soul of the Pure",
  DianKetoTheCureMaster = "Dian Keto the Cure Master",

  // power-up
  LegendarySword = "Legendary Sword",
  SwordOfDarkDestruction = "Sword of Dark Destruction",
  DarkEnergy = "Dark Energy",
  AxeOfDespair = "Axe of Despair",
  LaserCannonArmor = "Laser Cannon Armor",
  InsectArmorWithLaserCannon = "Insect Armor with Laser Cannon",
  ElfsLight = "Elf's Light",
  BeastFangs = "Beast Fangs",
  SteelShell = "Steel Shell",
  VileGerms = "Vile Germs",
  BlackPendant = "Black Pendant",
  SilverBowAndArrow = "Silver Bow and Arrow",
  HornOfLight = "Horn of Light",
  HornOfTheUnicorn = "Horn of the Unicorn",
  DragonTreasure = "Dragon Treasure",
  ElectroWhip = "Electro-Whip",
  CyberShield = "Cyber Shield",
  MysticalMoon = "Mystical Moon",
  MalevolentNuzzler = "Malevolent Nuzzler",
  VioletCrystal = "Violet Crystal",
  BookOfSecretArts = "Book of Secret Arts",
  Invigoration = "Invigoration",
  MachineConversionFactory = "Machine Conversion Factory",
  RaiseBodyHeat = "Raise Body Heat",
  FollowWind = "Follow Wind",
  PowerOfKaishin = "Power of Kaishin",
  KunaiWithChain = "Kunai with Chain",
  Salamandra = "Salamandra",
  Megamorph = "Megamorph",
  WingedTrumpeter = "Winged Trumpeter",
  BrightCastle = "Bright Castle",

  // monster-specific power-up
  CyclonLaser = "Cyclon Laser",
  ElegantEgotist = "Elegant Egotist",
  MagicalLabyrinth = "Magical Labyrinth",
  Cursebreaker = "Cursebreaker",
  Metalmorph = "Metalmorph",
  _7Completed = "7 Completed",

  // power-down
  SpellbindingCircle = "Spellbinding Circle",
  ShadowSpell = "Shadow Spell",

  // field
  Forest = "Forest",
  Wasteland = "Wasteland",
  Mountain = "Mountain",
  Sogen = "Sogen",
  Umi = "Umi",
  Yami = "Yami",

  // general card destruction
  FinalDestiny = "Final Destiny",
  HeavyStorm = "Heavy Storm",
  DarkHole = "Dark Hole",
  Raigeki = "Raigeki",
  CrushCard = "Crush Card",
  HarpiesFeatherDuster = "Harpie's Feather Duster",
  BeckonToDarkness = "Beckon to Darkness",

  // type-specific destruction
  WarriorElimination = "Warrior Elimination",
  EternalRest = "Eternal Rest",
  StainStorm = "Stain Storm",
  EradicatingAerosol = "Eradicating Aerosol",
  BreathOfLight = "Breath of Light",
  EternalDrought = "Eternal Drought",
  ExileOfTheWicked = "Exile of the Wicked",
  LastDayOfWitch = "Last Day of Witch",

  // assorted
  JamBreedingMachine = "Jam Breeding Machine",
  StopDefense = "Stop Defense",
  SwordsOfRevealingLight = "Swords of Revealing Light",
  DarkPiercingLight = "Dark-Piercing Light",
  MonsterReborn = "Monster Reborn",
  GravediggerGhoul = "Gravedigger Ghoul",
  MessengerOfPeace = "Messenger of Peace",
  DarknessApproaches = "Darkness Approaches",
  BrainControl = "Brain Control",
  ChangeOfHeart = "Change of Heart",
  Multiply = "Multiply",
  PotOfGreed = "Pot of Greed",
  TheInexperiencedSpy = "The Inexperienced Spy",
}

export enum Trap {
  DragonCaptureJar = "Dragon Capture Jar",
  DestinyBoard = "Destiny Board",
  SpiritMessageI = 'Spirit Message "I"',
  SpiritMessageN = 'Spirit Message "N"',
  SpiritMessageA = 'Spirit Message "A"',
  SpiritMessageL = 'Spirit Message "L"',
  AmazonArchers = "Amazon Archers",
  HouseOfAdhesiveTape = "House of Adhesive Tape",
  Eatgaboon = "Eatgaboon",
  BearTrap = "Bear Trap",
  InvisibleWire = "Invisible Wire",
  AcidTrapHole = "Acid Trap Hole",
  WidespreadRuin = "Widespread Ruin",
  GoblinFan = "Goblin Fan",
  BadReactionToSimochi = "Bad Reaction to Simochi",
  ReverseTrap = "Reverse Trap",
  FakeTrap = "Fake Trap",
  TorrentialTribute = "Torrential Tribute",
  InfiniteDismissal = "Infinite Dismissal",
  AntiRaigeki = "Anti Raigeki",
}

// this will error if an enum value doesn't match a card name
interface CheckCardName {
  [key: string]: CardName;
}
Monster as CheckCardName;
Spell as CheckCardName;
Trap as CheckCardName;
