type CardName =
  | "Blue-Eyes White Dragon"
  | "Mystical Elf"
  | "Hitotsu-Me Giant"
  | "Baby Dragon"
  | "Ryu-Kishin"
  | "Feral Imp"
  | "Winged Dragon, Guardian of the Fortress #1"
  | "Mushroom Man"
  | "Shadow Specter"
  | "Blackland Fire Dragon"
  | "Sword Arm of Dragon"
  | "Swamp Battleguard"
  | "The Stern Mystic"
  | "Battle Steer"
  | "Flame Swordsman"
  | "Time Wizard"
  | "Right Leg of the Forbidden One"
  | "Left Leg of the Forbidden One"
  | "Right Arm of the Forbidden One"
  | "Left Arm of the Forbidden One"
  | "Exodia the Forbidden One"
  | "Summoned Skull"
  | "The Wicked Worm Beast"
  | "Skull Servant"
  | "Horn Imp"
  | "Battle Ox"
  | "Beaver Warrior"
  | "Rock Ogre Grotto #1"
  | "Mountain Warrior"
  | "Zombie Warrior"
  | "Koumori Dragon"
  | "Two-Headed King Rex"
  | "Judge Man"
  | "Saggi the Dark Clown"
  | "Dark Magician"
  | "The Snake Hair"
  | "Gaia the Dragon Champion"
  | "Gaia The Fierce Knight"
  | "Curse of Dragon"
  | "Dragon Piper"
  | "Celtic Guardian"
  | "Illusionist Faceless Mage"
  | "Karbonala Warrior"
  | "Rogue Doll"
  | "Oscillo Hero #2"
  | "Griffore"
  | "Torike"
  | "Sangan"
  | "Big Insect"
  | "Basic Insect"
  | "Armored Lizard"
  | "Hercules Beetle"
  | "Killer Needle"
  | "Gokibore"
  | "Giant Flea"
  | "Larvae Moth"
  | "Great Moth"
  | "Kuriboh"
  | "Mammoth Graveyard"
  | "Great White"
  | "Wolf"
  | "Harpie Lady"
  | "Harpie Lady Sisters"
  | "Tiger Axe"
  | "Silver Fang"
  | "Kojikocy"
  | "Perfectly Ultimate Great Moth"
  | "Garoozis"
  | "Thousand Dragon"
  | "Fiend Kraken"
  | "Jellyfish"
  | "Cocoon of Evolution"
  | "Kairyu-Shin"
  | "Giant Soldier of Stone"
  | "Man-Eating Plant"
  | "Krokodilus"
  | "Grappler"
  | "Axe Raider"
  | "Megazowler"
  | "Uraby"
  | "Crawling Dragon #2"
  | "Red-Eyes B. Dragon"
  | "Castle of Dark Illusions"
  | "Reaper of the Cards"
  | "King of Yamimakai"
  | "Barox"
  | "Dark Chimera"
  | "Metal Guardian"
  | "Catapult Turtle"
  | "Gyakutenno Megami"
  | "Mystic Horseman"
  | "Rabid Horseman"
  | "Zanki"
  | "Crawling Dragon"
  | "Crass Clown"
  | "Armored Zombie"
  | "Dragon Zombie"
  | "Clown Zombie"
  | "Pumpking the King of Ghosts"
  | "Battle Warrior"
  | "Wings of Wicked Flame"
  | "Mask of Darkness"
  | "Baron of the Fiend Sword"
  | "Curtain of the Dark Ones"
  | "Tomozaurus"
  | "Spirit of the Winds"
  | "Shining Abyss"
  | "Headless Knight"
  | "Goddess with the Third Eye"
  | "Ruklamba the Spirit King"
  | "Doma The Angel of Silence"
  | "Keldo"
  | "Soldier Ari"
  | "White Magical Hat"
  | "Gearfried the Iron Knight"
  | "Nightmare Scorpion"
  | "Spirit of the Books"
  | "XYZ-Dragon Cannon"
  | "Humanoid Slime"
  | "Dream Clown"
  | "Sleeping Lion"
  | "Yamatano Dragon Scroll"
  | "Dark Plant"
  | "Worm Drake"
  | "Faith Bird"
  | "Orion the Battle King"
  | "Ansatsu"
  | "LaMoon"
  | "Nemuriko"
  | "Weather Control"
  | "Octoberser"
  | "Humanoid Worm Drake"
  | "Charubin the Fire Knight"
  | "Revival Jam"
  | "Fiend's Hand"
  | "Witty Phantom"
  | "Buster Blader"
  | "Dark Necrofear"
  | "Blue-Eyed Silver Zombie"
  | "Toad Master"
  | "Spiked Snail"
  | "Flame Manipulator"
  | "Necrolancer the Timelord"
  | "Djinn the Watcher of the Wind"
  | "The Bewitching Phantom Thief"
  | "Temple of Skulls"
  | "Monster Egg"
  | "The Shadow Who Controls the Dark"
  | "X-Head Cannon"
  | "Akihiron"
  | "Orgoth the Relentless"
  | "The Melting Red Shadow"
  | "Dokuroizo the Grim Reaper"
  | "Fire Reaper"
  | "Larvas"
  | "Hard Armor"
  | "Firegrass"
  | "Cyber Jar"
  | "Dig Beak"
  | "M-Warrior #1"
  | "M-Warrior #2"
  | "Banisher of the Light"
  | "Lisark"
  | "Des Feral Imp"
  | "The Judgement Hand"
  | "Mysterious Puppeteer"
  | "Ancient Jar"
  | "Darkfire Dragon"
  | "Dark King of the Abyss"
  | "Spirit of the Harp"
  | "Big Eye"
  | "Armaill"
  | "Giant Rat"
  | "Senju of the Thousand Hands"
  | "UFO Turtle"
  | "Fire Eye"
  | "Monsturtle"
  | "Claw Reacher"
  | "Phantom Dewan"
  | "Arlownay"
  | "Flash Assailant"
  | "Karate Man"
  | "Lucky Trinket"
  | "Genin"
  | "Dark Zebra"
  | "Fiend Reflection #2"
  | "Gate Deeg"
  | "Giant Germ"
  | "Fusionist"
  | "Nimble Momonga"
  | "LaLa Li-oon"
  | "Key Mace"
  | "Final Destiny"
  | "Heavy Storm"
  | "Doron"
  | "Cyclon Laser"
  | "Boar Soldier"
  | "Happy Lover"
  | "Penguin Knight"
  | "Petit Dragon"
  | "Frenzied Panda"
  | "Air Marmot of Nefariousness"
  | "Phantom Ghost"
  | "Mother Grizzly"
  | "Flying Kamakiri #1"
  | "Twin Long Rods #1"
  | "Droll Bird"
  | "Petit Angel"
  | "Winged Cleaver"
  | "Hinotama Soul"
  | "Kaminarikozou"
  | "Meotoko"
  | "Aqua Madoor"
  | "Kagemusha of the Blue Flame"
  | "Flame Ghost"
  | "Nightmare Penguin"
  | "B. Skull Dragon"
  | "Two-Mouth Darkruler"
  | "Solitude"
  | "Masked Sorcerer"
  | "Kumootoko"
  | "Ceremonial Bell"
  | "Roaring Ocean Snake"
  | "Trap Master"
  | "Fiend Sword"
  | "Sonic Bird"
  | "Mystic Tomato"
  | "Wood Remains"
  | "Hourglass of Life"
  | "Rare Fish"
  | "Wood Clown"
  | "Kotodama"
  | "Jam Breeding Machine"
  | "Obelisk the Tormentor"
  | "Wodan the Resident of the Forest"
  | "Perfect Machine King"
  | "Haniwa"
  | "Slifer the Sky Dragon"
  | "Vishwar Randi"
  | "The Winged Dragon of Ra (Battle Mode)"
  | "Dark Assailant"
  | "Candle of Fate"
  | "Water Element"
  | "Dissolverock"
  | "Flying Fish"
  | "One Who Hunts Souls"
  | "Root Water"
  | "Amphibian Beast"
  | "Water Omotics"
  | "Alligator's Sword Dragon"
  | "Enchanting Mermaid"
  | "Nekogal #1"
  | "Rocket Warrior"
  | "Aqua Serpent"
  | "Prevent Rat"
  | "Dimensional Warrior"
  | "The Legendary Fisherman"
  | "Beastking of the Swamps"
  | "Satellite Cannon"
  | "Lunar Queen Elzaim"
  | "Wicked Mirror"
  | "The Little Swordsman of Aile"
  | "Rock Ogre Grotto #2"
  | "Wing Egg Elf"
  | "The Furious Sea King"
  | "Princess of Tsurugi"
  | "Morphing Jar #2"
  | "Vorse Raider"
  | "Versago the Destroyer"
  | "Wetha"
  | "Megirus Light"
  | "Mavelus"
  | "Ancient Tree of Enlightenment"
  | "Green Phantom King"
  | "Ground Attacker Bugroth"
  | "Ray & Temperature"
  | "Flame Champion"
  | "Petit Moth"
  | "Twin-Headed Fire Dragon"
  | "Darkfire Soldier #1"
  | "Mystic Clown"
  | "Mystical Sheep #2"
  | "Holograh"
  | "Tao the Chanter"
  | "Serpent Marauder"
  | "Mr. Volcano"
  | "Ogre of the Black Shadow"
  | "Darkfire Soldier #2"
  | "Change Slime"
  | "Moon Envoy"
  | "Fireyarou"
  | "Kiseitai"
  | "Masaki the Legendary Swordsman"
  | "Dragoness the Wicked Knight"
  | "Cyber Falcon"
  | "One-Eyed Shield Dragon"
  | "The Winged Dragon of Ra (Sphere Mode)"
  | "Wicked Dragon with the Ersatz Head"
  | "Sonic Maid"
  | "Kurama"
  | "Legendary Sword"
  | "Sword of Dark Destruction"
  | "Dark Energy"
  | "Axe of Despair"
  | "Laser Cannon Armor"
  | "Insect Armor with Laser Cannon"
  | "Elf's Light"
  | "Beast Fangs"
  | "Steel Shell"
  | "Vile Germs"
  | "Black Pendant"
  | "Silver Bow and Arrow"
  | "Horn of Light"
  | "Horn of the Unicorn"
  | "Dragon Treasure"
  | "Electro-Whip"
  | "Cyber Shield"
  | "Elegant Egotist"
  | "Mystical Moon"
  | "Stop Defense"
  | "Malevolent Nuzzler"
  | "Violet Crystal"
  | "Book of Secret Arts"
  | "Invigoration"
  | "Machine Conversion Factory"
  | "Raise Body Heat"
  | "Follow Wind"
  | "Power of Kaishin"
  | "Dragon Capture Jar"
  | "Forest"
  | "Wasteland"
  | "Mountain"
  | "Sogen"
  | "Umi"
  | "Yami"
  | "Dark Hole"
  | "Raigeki"
  | "Mooyan Curry"
  | "Red Medicine"
  | "Goblin's Secret Remedy"
  | "Soul of the Pure"
  | "Dian Keto the Cure Master"
  | "Sparks"
  | "Hinotama"
  | "Final Flame"
  | "Ookazi"
  | "Tremendous Fire"
  | "Swords of Revealing Light"
  | "Spellbinding Circle"
  | "Dark-Piercing Light"
  | "Yaranzo"
  | "Kanan the Swordmistress"
  | "Takriminos"
  | "Stuffed Animal"
  | "Megasonic Eye"
  | "Super War-Lion"
  | "Yamadron"
  | "Seiyaryu"
  | "Three-Legged Zombies"
  | "Zera The Mant"
  | "Flying Penguin"
  | "Millennium Shield"
  | "Fairy's Gift"
  | "Black Luster Soldier"
  | "Fiend's Mirror"
  | "Labyrinth Wall"
  | "Jirai Gumo"
  | "Shadow Ghoul"
  | "Wall Shadow"
  | "Labyrinth Tank"
  | "Sanga of the Thunder"
  | "Kazejin"
  | "Suijin"
  | "Gate Guardian"
  | "Dungeon Worm"
  | "Monster Tamer"
  | "Ryu-Kishin Powered"
  | "Swordstalker"
  | "La Jinn the Mystical Genie of the Lamp"
  | "Blue-Eyes Ultimate Dragon"
  | "Toon Alligator"
  | "Rude Kaiser"
  | "Parrot Dragon"
  | "Dark Rabbit"
  | "Bickuribox"
  | "Harpie's Pet Dragon"
  | "Mystic Lamp"
  | "Pendulum Machine"
  | "Giltia the D. Knight"
  | "Launcher Spider"
  | "Zoa"
  | "Metalzoa"
  | "Zone Eater"
  | "Steel Scorpion"
  | "Dancing Elf"
  | "Ocubeam"
  | "Leghul"
  | "Ooguchi"
  | "Gamma The Magnet Warrior"
  | "Emperor of the Land and Sea"
  | "Ushi Oni"
  | "Monster Eye"
  | "Leogun"
  | "Tatsunootoshigo"
  | "Saber Slasher"
  | "Kaiser Sea Horse"
  | "Machine King"
  | "Giant Mech-Soldier"
  | "Metal Dragon"
  | "Mechanical Spider"
  | "Bat"
  | "The Winged Dragon of Ra (Phoenix Mode)"
  | "Cyber Soldier"
  | "Shovel Crusher"
  | "Mechanicalchaser"
  | "Blocker"
  | "Blast Juggler"
  | "Golgoil"
  | "Flying Kamakiri #2"
  | "Cyber-Stein"
  | "Cyber Commander"
  | "Jinzo #7"
  | "Dice Armadillo"
  | "Sky Dragon"
  | "Thunder Dragon"
  | "Stone D."
  | "Kaiser Dragon"
  | "Magician of Faith"
  | "Goddess of Whim"
  | "Gradius"
  | "Ice Water"
  | "Waterdragon Fairy"
  | "Ancient Elf"
  | "Harpie's Brother"
  | "Aeris"
  | "White Dolphin"
  | "Deepsea Shark"
  | "Metal Fish"
  | "Grand Tiki Elder"
  | "7 Colored Fish"
  | "Mech Bass"
  | "Aqua Dragon"
  | "Sea King Dragon"
  | "Turu-Purun"
  | "Giant Rex"
  | "Aqua Snake"
  | "Giant Red Seasnake"
  | "Spike Seadra"
  | "30,000-Year White Turtle"
  | "Kappa Avenger"
  | "Kanikabuto"
  | "Zarigun"
  | "Millennium Golem"
  | "Destroyer Golem"
  | "Barrel Rock"
  | "Minomushi Warrior"
  | "The Masked Beast"
  | "Kaminari Attack"
  | "Tripwire Beast"
  | "Bolt Escargot"
  | "Bolt Penguin"
  | "The Immortal of Thunder"
  | "Electric Snake"
  | "Wing Eagle"
  | "Punished Eagle"
  | "Skull Red Bird"
  | "Crimson Sunbird"
  | "Queen Bird"
  | "Armed Ninja"
  | "Magical Ghost"
  | "Soul Hunter"
  | "The Earl of Demise"
  | "Vermillion Sparrow"
  | "Sea Kamen"
  | "Sinister Serpent"
  | "Ganigumo"
  | "Alinsection"
  | "Insect Soldiers of the Sky"
  | "Cockroach Knight"
  | "Kuwagata A"
  | "Burglar"
  | "Pragtical"
  | "Garvas"
  | "Ameba"
  | "Korogashi"
  | "Boo Koo"
  | "Flower Wolf"
  | "Rainbow Flower"
  | "Barrel Lily"
  | "Needle Ball"
  | "Peacock"
  | "Hoshiningen"
  | "Maha Vailo"
  | "Rainbow Marine Mermaid"
  | "Musician King"
  | "Wilmee"
  | "Yado Karu"
  | "Morinphen"
  | "Boneheimer"
  | "Dragon Seeker"
  | "Man-Eater Bug"
  | "Penguin Torpedo"
  | "Turtle Raccoon"
  | "Flame Dancer"
  | "Prisman"
  | "Gale Dogra"
  | "Crazy Fish"
  | "Cyber Saurus"
  | "Bracchio-raidus"
  | "Laughing Flower"
  | "Bean Soldier"
  | "Cannon Soldier"
  | "Guardian of the Throne Room"
  | "Asura Priest"
  | "The Statue of Easter Island"
  | "Muka Muka"
  | "Zombyra the Dark"
  | "Boulder Tortoise"
  | "Fire Kraken"
  | "Turtle Bird"
  | "Skullbird"
  | "Monstrous Bird"
  | "The Bistro Butcher"
  | "Star Boy"
  | "Spirit of the Mountain"
  | "Earthbound Spirit"
  | "Milus Radiant"
  | "Togex"
  | "Flame Cerebrus"
  | "Embodiment of Apophis"
  | "Mystical Sand"
  | "Gemini Elf"
  | "Kwagar Hercules"
  | "Minar"
  | "Ancient Lamp"
  | "Mechaleon"
  | "Mega Thunderball"
  | "Niwatori"
  | "Amazon Chain Master"
  | "Skelengel"
  | "Hane-Hane"
  | "Misairuzame"
  | "Thunder Nyan Nyan"
  | "Dharma Cannon"
  | "Skelgon"
  | "Wow Warrior"
  | "Griggle"
  | "Bone Mouse"
  | "Frog the Jam"
  | "Last Tusk Mammoth"
  | "Dark Elf"
  | "Winged Dragon, Guardian of the Fortress #2"
  | "Mushroom Man #2"
  | "Lava Battleguard"
  | "Queen's Knight"
  | "Injection Fairy Lily"
  | "Jack's Knight"
  | "Pot the Trick"
  | "Oscillo Hero"
  | "Invader from Another Dimension"
  | "Lesser Dragon"
  | "Needle Worm"
  | "King's Knight"
  | "Great Mammoth of Goldfine"
  | "Gil Garth"
  | "Yormungarde"
  | "Darkworld Thorns"
  | "Blade Knight"
  | "Gernia"
  | "Trakadon"
  | "B. Dragon Jungle King"
  | "Empress Judge"
  | "Little D"
  | "Witch of the Black Forest"
  | "Y-Dragon Head"
  | "Giant Scorpion of the Tundra"
  | "Crow Goblin"
  | "Dark Magician Knight"
  | "Abyss Flower"
  | "Patrol Robo"
  | "Takuhee"
  | "Dark Witch"
  | "Destiny Board"
  | 'Spirit Message "I"'
  | 'Spirit Message "N"'
  | 'Spirit Message "A"'
  | 'Spirit Message "L"'
  | "Living Vase"
  | "Tentacle Plant"
  | "Z-Metal Tank"
  | "Morphing Jar"
  | "Muse-A"
  | "XY-Dragon Cannon"
  | "Rose Spectre of Dunn"
  | "Fiend Reflection #1"
  | "XZ-Tank Cannon"
  | "YZ-Tank Dragon"
  | "Little Chimera"
  | "Violent Rain"
  | "Exodia Necross"
  | "Monster Reborn"
  | "Penguin Soldier"
  | "Fairy Dragon"
  | "Helpoemer"
  | "Lava Golem"
  | "Newdoria"
  | "Dark Jeroid"
  | "Shining Friendship"
  | "Gravedigger Ghoul"
  | "Electric Lizard"
  | "Hiro's Shadow Scout"
  | "Lady of Faith"
  | "Twin-Headed Thunder Dragon"
  | "Hunter Spider"
  | "Armored Starfish"
  | "Executor - Makyura"
  | "Marine Beast"
  | "Warrior of Tradition"
  | "Byser Shock"
  | "Snakeyashi"
  | "Succubus Knight"
  | "Ill Witch"
  | "Viser Des"
  | "High Tide Gyojin"
  | "Fairy of the Fountain"
  | "Amazon of the Seas"
  | "Nekogal #2"
  | "Witch's Apprentice"
  | "Puppet Master"
  | "Amazon Fighter"
  | "Maiden of the Moonlight"
  | "Stone Ogre Grotto"
  | "Amazon Sword Woman"
  | "Vampire Lord"
  | "Queen's Double"
  | "Dark Paladin"
  | "Trent"
  | "Queen of Autumn Leaves"
  | "Amphibious Bugroth"
  | "Different Dimension Dragon"
  | "Amazon Archers"
  | "Mystical Sheep #1"
  | "Yamata Dragon"
  | "Shinato, King of a Higher Plane"
  | "Dark Flare Knight"
  | "Mirage Knight"
  | "Berserk Dragon"
  | "Machine Attacker"
  | "Command Angel"
  | "Whiptail Crow"
  | "Kunai with Chain"
  | "Magical Labyrinth"
  | "Warrior Elimination"
  | "Salamandra"
  | "Cursebreaker"
  | "Eternal Rest"
  | "Megamorph"
  | "Metalmorph"
  | "Winged Trumpeter"
  | "Stain Storm"
  | "Crush Card"
  | "Eradicating Aerosol"
  | "Breath of Light"
  | "Eternal Drought"
  | "Des Volstgalph"
  | "Toon Dark Magician Girl"
  | "Gilford the Lightning"
  | "Bright Castle"
  | "Shadow Spell"
  | "Black Luster Ritual"
  | "Mystical Beast Serket"
  | "Harpie's Feather Duster"
  | "Cyber Harpie"
  | "Lightning Conger"
  | "Exarion Universe"
  | "Legendary Fiend"
  | "Gadget Soldier"
  | "Melchid the Four-Face Beast"
  | "Nuvia the Wicked"
  | "Masked Beast Des Gardius"
  | "House of Adhesive Tape"
  | "Eatgaboon"
  | "Bear Trap"
  | "Invisible Wire"
  | "Acid Trap Hole"
  | "Widespread Ruin"
  | "Goblin Fan"
  | "Bad Reaction to Simochi"
  | "Reverse Trap"
  | "Fake Trap"
  | "Valkyrion the Magna Warrior"
  | "Torrential Tribute"
  | "Beckon to Darkness"
  | "Infinite Dismissal"
  | "7 Completed"
  | "Dark Sage"
  | "F.G.D."
  | "Master of Dragon Soldier"
  | "Messenger of Peace"
  | "Darkness Approaches"
  | "Performance of Sword"
  | "Hungry Burger"
  | "Sengenjin"
  | "Skull Guardian"
  | "Tri-Horned Dragon"
  | "Serpent Night Dragon"
  | "Skull Knight"
  | "Cosmo Queen"
  | "Chakra"
  | "Crab Turtle"
  | "Mikazukinoyaiba"
  | "Meteor Dragon"
  | "Meteor B. Dragon"
  | "Firewing Pegasus"
  | "Psycho-Puppet"
  | "Garma Sword"
  | "Javelin Beetle"
  | "Fortress Whale"
  | "Dokurorider"
  | "Mask of Shine & Dark"
  | "Magician of Black Chaos"
  | "Dark Magic Ritual"
  | "Slot Machine"
  | "Space Megatron"
  | "Red Archery Girl"
  | "Ryu-Ran"
  | "Manga Ryu-Ran"
  | "Toon Mermaid"
  | "Toon Summoned Skull"
  | "Dark-Eyes Illusionist"
  | "Relinquished"
  | "Jigen Bakudan"
  | "Thousand-Eyes Idol"
  | "Thousand-Eyes Restrict"
  | "Steel Ogre Grotto #2"
  | "Blast Sphere"
  | "Hyozanryu"
  | "Alpha The Magnet Warrior"
  | "Legion the Fiend Jester"
  | "Invitation to a Dark Sleep"
  | "Lord of D."
  | "Red-Eyes Black Metal Dragon"
  | "Barrel Dragon"
  | "Hannibal Necromancer"
  | "Panther Warrior"
  | "Three-Headed Geedo"
  | "Gazelle the King of Mythical Beasts"
  | "Stone Statue of the Aztecs"
  | "Berfomet"
  | "Chimera the Flying Mythical Beast"
  | "Gear Golem the Moving Fortress"
  | "Jinzo"
  | "Swordsman of Landstar"
  | "Cyber Raider"
  | "The Fiend Megacyber"
  | "Reflect Bounder"
  | "Beta The Magnet Warrior"
  | "Big Shield Gardna"
  | "Doll of Demise"
  | "Dark Magician Girl"
  | "Alligator's Sword"
  | "Insect Queen"
  | "Parasite Paracide"
  | "Skull-Mark Lady Bug"
  | "Tiny Guardian"
  | "Pinch Hopper"
  | "Blue-Eyes Toon Dragon"
  | "The Unhappy Maiden"
  | "Wall of Illusion"
  | "Neo the Magic Swordsman"
  | "Man-Eating Treasure Chest"
  | "Chiron the Mage"
  | "Sword Hunter"
  | "Drill Bug"
  | "Deepsea Warrior"
  | "Bite Shoes"
  | "Spikebot"
  | "Beast of Gilfer"
  | "The Portrait's Secret"
  | "The Gross Ghost of Fled Dreams"
  | "Brain Control"
  | "Anti Raigeki"
  | "Black Illusion Ritual"
  | "Change of Heart"
  | "Multiply"
  | "Exile of the Wicked"
  | "Last Day of Witch"
  | "Restructer Revolution"
  | "Pot of Greed"
  | "The Inexperienced Spy"
  | "Gate Sword"
  | "Steel Fan Fighter"
  | "Leopard Girl"
  | "The Last Warrior from Another Planet"
  | "Dunames Dark Witch"
  | "Garnecia Elefantis"
  | "Total Defense Shogun"
  | "Beast of Talwar"
  | "Cyber-Tech Alligator"
  | "Talons of Shurilane";
