interface Duellable {
  name: DuellableName;
  deck: CardQuantityMap;
  lp: number;
  location: string;
  payout: number;
  dc: 0 | 1 | 3 | 10 | 20;
  field: Field;
  ante: CardName[];
  inRoute: boolean;
}

type CardQuantityMap = {
  [card in CardName]?: number;
};

type DuellableName =
  | "Player (Initial Deck)"
  | "Player (Initial Trunk)"
  | "Yugi Muto"
  | "Joey Wheeler"
  | "Tristan Taylor"
  | "Duke Devlin 1"
  | "Rebecca"
  | "Roland"
  | "Mokuba"
  | "Duel Computer (Novice)"
  | "Duel Computer (Standard)"
  | "Duel Computer (Expert)"
  | "Red hat (DR)"
  | "Blue clothes 1 (DR)"
  | "Purple hair (DRU)"
  | "Lint Greendale 1 (DRR)"
  | "Blue jacket (DRR)"
  | "Blond 1 (DRRU)"
  | "Red hair 1 (DDRR)"
  | "Purple shirt (DDRR)"
  | "Blue overalls (DDR)"
  | "Stringer 1 (DD)"
  | "Conductor (Turnstyles)"
  | "Feng Long"
  | "Long brown hair (Platform)"
  | "Spikey black hair (Platform)"
  | "Black ponytail (Platform)"
  | "Bowlcut (Platform)"
  | "Conductor (Platform)"
  | "Damien Draco"
  | "Headband guy (Train)"
  | "Conductor (Train)"
  | "PaniK 1"
  | "Upper-class girl"
  | "Upper-class father"
  | "Kaiba impersonator 1"
  | "Millennium Guardian 1"
  | "Puppeteer of Doom"
  | "Hobson"
  | "Takeshi"
  | "Jean-Claude Magnum 1"
  | "Casino Wife 1"
  | "Mai 1"
  | "Millennium Guardian 2"
  | "Bonz 1"
  | "Millennium Guardian 3"
  | "Para 1"
  | "Para 2"
  | "Dox 1"
  | "Millennium Guardian 4"
  | "Jinzo"
  | "Johnny Steps"
  | "Crump"
  | "Glasses (Canada)"
  | "Blue jeans 1 (Canada)"
  | "Rex 1"
  | "Millennium Guardian 5"
  | "Mako 1"
  | "Weevil 1"
  | "Mimic of Doom 1"
  | "Monkey #1"
  | "Monkey #2"
  | "Monkey #3"
  | "Monkey #4"
  | "Rare Hunter 1"
  | "Ghoul (DDRR - left)"
  | "Ghoul (DDRR - right)"
  | "Ghoul (DDR)"
  | "Ghoul (DD)"
  | "Ghoul (DRR)"
  | "Ghoul (DR)"
  | "Ghoul (Station)"
  | "Arkana"
  | "Ghoul at Bonz"
  | "Ghoul right of Rex"
  | "Ghoul left of Rex"
  | "Lumis"
  | "Umbra"
  | "Strings"
  | "Rare Hunter 2"
  | "Mini Ghoul 1"
  | "Mini Ghoul 2"
  | "Mini Ghoul 3"
  | "Mini Ghoul 4"
  | "Mini Ghoul 5"
  | "Bandit Keith"
  | "Duke Devlin 2"
  | "Red hair 2 (DD)"
  | "Stringer 2 (DD)"
  | "Blue clothes 2 (DR)"
  | "Lint Greendale 2 (DRR)"
  | "Blond 2 (DRRU)"
  | "Red hair 2 (DDRR)"
  | "Espa 1"
  | "Kaiba impersonator 2"
  | "Jean-Claude Magnum 2"
  | "Casino Wife 2"
  | "Casino Husband"
  | "Mai 2"
  | "Bonz 2"
  | "Blue jeans 2 (Canada)"
  | "Rex 2"
  | "Mako 2"
  | "Weevil 2"
  | "Odion"
  | "Marik Ishtar"
  | "Paradox Guardian 1"
  | "Paradox Guardian 2"
  | "Paradox Guardian 3"
  | "Paradox Guardian 4"
  | "Paradox Guardian 5"
  | "Paradox"
  | "Chevaliers (Cable Car)"
  | "PaniK 2"
  | "Mimic of Doom 2"
  | "Chevalier 1 (West)"
  | "Chevalier 1 (East)"
  | "Chevalier 2 (West)"
  | "Chevalier 2 (East)"
  | "Chevalier 3 (West)"
  | "Chevalier 3 (East)"
  | "Para 3"
  | "Dox 2"
  | "Chevalier 4"
  | "Bonz 3"
  | "Rex 3"
  | "Weevil 3"
  | "Mako 3"
  | "Mai 3"
  | "Espa 2"
  | "Bonz (Imposter)"
  | "Rex (Imposter)"
  | "Weevil (Imposter)"
  | "Mako (Imposter)"
  | "Espa (Imposter)"
  | "Mai (Imposter)"
  | "Dark Mokuba"
  | "Seto Kaiba"
  | "Sol Chevalsky"
  | "Reshef"
  | "Pegasus (HoE)"
  | "Seto Kaiba (HoE)"
  | "Dark Joey (HoE)"
  | "Yami Bakura (HoE)"
  | "Yami Yugi (HoE)"
  | "Yami Marik (HoE)"
  | "Noah (HoE)"
  | "Shadi (HoE)"
  | "Paradox (HoE)";
